apiVersion: v1
kind: Pod
metadata:
  name: vault
  labels:
    app: vault
spec:
  containers:
  - name: vault
    image: hashicorp/vault:latest
    env:
    - name: VAULT_DEV_ROOT_TOKEN_ID
      value: "dev-root-token"
    - name: VAULT_DEV_LISTEN_ADDRESS
      value: "0.0.0.0:8200"
    ports:
    - containerPort: 8200
      name: vault
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  type: NodePort
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
    nodePort: 30200
    protocol: TCP
